name: bionetviz
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - pyyaml=6.*
  - flask=2.2.*
  - networkx=3.*
  - numpy=1.24.*
  - pandas=2.0.*
  - monotonic=1.*
  - neo4j-python-driver=5.7.*
  - black=23.3.*
  - mpmath=1.3.0.*
  - backports.functools_lru_cache=1.6.4.*
  - networkit=10.1.*
  - pre-commit=3.7.*
  - python-dotenv
  - pip
  - pip:
    - mygene
    - meilisearch
    - transformers
    - igraph
    - leidenalg
    - torch
    - ollama
    - langchain-ollama
